### ISSUE TITLE
"import.meta.url" is undefined in ".mjs" files.

### ISSUE THREAD

**Issue by sumihiro** [serverless/serverless#10929]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

1. Create project using 'aws-nodejs-typescript' template.
2. Create 'src/functions/hello/mod.mjs' file, and references 'import.meta.url'.
3. Invoke 'hello' function. 'import.meta.url' should be a file URL, but it is undefined.

I created a sample project.

https://github.com/sumihiro/serverless-aws-nodejs-typescript/blob/892003ed7b8866f5c4f8b5f616ff43e41aa0e77c/src/functions/hello/mod.mjs#L1

This line should output the file URL, but it is undefined.

### Service configuration (serverless.yml) content

```yaml
import type { AWS } from '@serverless/typescript';

import hello from '@functions/hello';

const serverlessConfiguration: AWS = {
  service: 'aws-nodejs-typescript',
  frameworkVersion: '3',
  plugins: ['serverless-esbuild'],
  provider: {
    name: 'aws',
    runtime: 'nodejs14.x',
    apiGateway: {
      minimumCompressionSize: 1024,
      shouldStartNameWithService: true,
    },
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000',
    },
  },
  // import the function via paths
  functions: { hello },
  package: { individually: true },
  custom: {
    esbuild: {
      bundle: true,
      minify: false,
      sourcemap: true,
      exclude: ['aws-sdk'],
      target: 'node14',
      define: { 'require.resolve': undefined },
      platform: 'node',
      concurrency: 10,
    },
  },
};

module.exports = serverlessConfiguration;
```

### Command name and used flags

sls invoke local --function hello

### Command output

```shell
undefined // <- should be a file URL
{}
{
    "statusCode": 200,
    "body": "{\"message\":\"Hello , welcome to the exciting Serverless world!\",\"event\":\"\"}"
}
```

### Environment information

```shell
Framework Core: 3.11.0 (local) 3.7.1 (global)
Plugin: 6.2.1
SDK: 4.3.2
```
