### ISSUE TITLE
Resolver does not reload variable meta

### ISSUE THREAD

**Issue by mklenbw** [serverless/serverless#11034]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest version?

- [X] Yes, I'm using the latest version

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

If a plugin changes or adds contents of the configuration (serverless.service) the variables are not resolved as the variablesMeta is just created at start.

The problem can be solved by just running and merging variablesMeta before the last resolveVariables-call.

`scripts/serverless.js`
![image](https://user-images.githubusercontent.com/87859452/166935719-53e9f477-62a4-4282-902d-797b69138e06.png)

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

serverless package

### Command output

```shell
N/A
```

### Environment information

```shell
Framework Core: 3.16.0 (local)
Plugin: 6.2.2
SDK: 4.3.2
```

**Comment by medikoo** [comment]
@mklenbw by design variables meta is resolved once and its prior plugins initialization. Plugins if are extending the configuration are expected to provide resolved values (not behind variables)

What use case you're addressing?

**Comment by mklenbw** [comment]
We implemented a plugin which installs template modules from a repository (like serverless-modularize with backend). These can contain variables like any other serverless-file (refs to custom variables etc.). If it's needed to resolve these we'd need to reimplement the resolver.

As the resolving is done multiple times why not the scanning of the variablesMeta. (Although i would love to have resolving after every lifecycle event)

**Comment by medikoo** [comment]
> We implemented a plugin which installs template modules from a repository

Thanks @mklenbw are those templates an extensions to `serverless.yml` ? Or is it about some multi-service architecture?

**Comment by mklenbw** [comment]
Those are extensions. Mostly cloudformation encapsulated by own serverless.yml files. These are merged at startup to the main  serverless. We use custom properties to implement an interface for these "modules" and have them exchangeable and configurable. 
We use this plugin to abstract most of the basic infrastructure we need  (authentication, apis, domains) and speed up application setup so developers can fokus on their code.

**Comment by medikoo** [comment]
@mklenbw have you considered introducing custom [variable source](https://www.serverless.com/framework/docs/guides/plugins/custom-variables). If variable source return an object with properties behind variables, the resolver will automatically resolve them

then user may use extensions as:

```yaml
custom:
  someConfig: ${ext:name}
```

And if `ext` source returns structure with variables, they will be resolved

**Comment by mklenbw** [comment]
That's what we do as a workaround. But it's not very pleasant for our customers as they are installing a bunch of modules with own dependencies And it worked with the old version, so why would they consider an update to serverless v3.

**Comment by medikoo** [comment]
> And it worked with the old version, so why would they consider an update to serverless v3.

Yes that was possible with older version, but it's because the variable resolution was made then after the initial setup, which raised many issues, as many users used variables for properties that play part in that initial setup, and then things either don't work, or unexpected things happen.

With the new resolver, the variable resolution starts after configuration is retrieved (so before plugins are loaded) and then additional stages of resolution are added as new things are set up.

There's the last step of resolution made after plugins are loaded, so technically plugins are free to extend the configuration with properties behind variables, but it needs to be done in a way that the variable resolver is aware of.

> If you want, we can show you. We're a big german company relying solely on serverless for our infrastructure. Just schedule something with your support.

Yes, it'll be great if you provide more details explaining why exactly using a custom variable source feels not great for your case. I'm pretty sure we can work out something.

**Comment by mnapoli** [comment]
Separately from this discussion, @mklenbw I'm interested in learning more about your modular architecture system. Could you send me an email at matthieu.napoli at serverless dot com ?

**Comment by mklenbw** [comment]
> @mklenbw best if you explain in the context of this issue. Ideally, if use case approach you currently take is clearly described
> 
> From the info you've provided, it seems that a custom variable source should solve it, but you state it's not ideal, yet I don't have details why it's not

Let my try to give an example, but i will simplify some things for better understanding.

We have one module file containing configuration and resources of a certain functionality.
Let's call it `serverless.module.yml`.

``` yaml
custom:
  myModule:
     logGroupName: ${self:custom.resourcePrefix}-logGroup

     logGroupArn: !GetAtt ModuleResource.Arn

resources:
  Resources:
    ModuleResource:
      Type: AWS::Logs::LogGroup
      Properties: 
        LogGroupName: ${self:custom.myModule.logGroupName}
        RetentionInDays: 1
```

Then we have our main `serverless.yml`:

```
service: example-service

plugins:
  - serverless-module-manager

moduleManager:
  modules:
    - serverless.module.yml

provider:
  name: aws

custom:
  resourcePrefix: "${self:service}--${self:provider.stage}"
```

Now what happens with our Plugin is it takes the specified modules and merges it to the main configuration. But this will leave all variables of the `serverless.module.yml` unresolved. In serverless v2 i resolved the merged content myself with the `resolveObject` method of the `Variables` class.

In reality this is a bit more complex as these module files can be defined locally or can be served through some kind of a repository and have versioning and depency-management.

**Comment by medikoo** [comment]
@mklenbw great thanks for the explanations, it's all clearer now. I understand that idea is to group reusable parts of a configuration as modules, which can be referenced in the service configuration, and then plugin would be responsible to read them and extend the configuration with their content.

Users solve it mostly via `${file..}` variable source, but I see it's not as convenient in your case, as you'd have to separately import each extended property in the target configuration, and that doesn't play well when we want to handle modules generically.

One special aspect of your approach is that with modules technically you may address already existing parts of the configuration. If the plugin will allow us to overwrite them, then we may end with a configuration totally different from one that was processed to this point, when internals already consumed some core properties (as `service`, `provider.name` etc.)

If we were to allow such dynamic changes to the configuration, then after loading plugins we'd have to consider all information we've gathered so far as unreliable and need to restart the whole initialization process from the scratch, that's definitely a no-go (putting aside that we'd end in an infinite loop here)

Still, I assume that you're more after extending properties that are safe to manipulate at the point of plugin initialization, and that's definitely doable.

Problem is that currently adding new properties configured behind variables is only possible through variable sources, but we can improve that.  As I think of it, we may add `serverless.extendConfiguration(propertyPathKeys, value)` method, which you may use in Plugin constructor (and not later).

Having that your plugin in its constructor may call:

```javascript
serverless.extendConfiguration(['custom', 'myModule'], {
  logGroupName: '${self:custom.resourcePrefix}-logGroup'),
  logGroupArn: '!GetAtt ModuleResource.Arn'
});
serverless.extendConfiguration(['resources', 'Resources', 'ModuleResource'], {
  Type: "AWS::Logs::LogGroup"
});
```

And then engine will guarantee all new properties will have their variables resolved.

Will that solve the issue for you?

**Comment by mklenbw** [comment]
Wow. Your sugggestion would be a great feature as it allowed to securely extend the configuration. I would love to have such a feature and i guess it would bring up new great types of plugins.

Construction is a great place because it's basically the only one that is save to alter the configuration as i understood. If i have to add configuration for other plugins they would have to be ordered after our plugin.
As all internal configuration are already read at that point the extension of this should not have any effect on the internal things. But there are plugins like the aws-provider which take up some things later in stage like the alb.authorizers and this should be considered safe to change.

I really get the point of breaking the configuration, but in the end the plugin developer should be responsible of this. I love the openness of your framework and the possibilities it gives me as a plugin developer. This makes it so great.

Thanks. If you need something or i can help testing just contact me.

**Comment by medikoo** [comment]
Great to hear that. I propose to add support for `serverless.extendConfiguration` then.

@mnapoli @pgrzesik what do you think?

**Comment by pgrzesik** [comment]
That sounds like a really good proposal, I think it will be useful for potentially enabling plugins that allow injecting reusable parts of configuration in a more user-friendly manner 👍

**Comment by mklenbw** [comment]
Something new here?

We implemented the fix in a fork and are now using our own serverless version. Everything works as expected.

**Comment by icholy** [comment]
I am also affected by this. We use a custom plugin to manage environment variables across 100's of services. The variables are no longer resolved after updating to serverless v3.

**Comment by medikoo** [comment]
@icholy, we're fine in adding support for `serverless.extendConfiguration` I agree that, indeed, it's crucial to ensure full operability with variables resolver. Still, internally we do not have the resources to address that promptly.

If anyone is keen on working on that, I'll be happy to provide instructions on how to implement it

**Comment by icholy** [comment]
@medikoo I can work on this.

**Comment by medikoo** [comment]
@icholy great to hear that!

Hints on how to achieve that:
- Expose [`variablesMeta`] (https://github.com/serverless/serverless/blob/65e9860838de40c8ef0189c723e09936c8ca71a7/scripts/serverless.js#L246) to [`Serverless`](https://github.com/serverless/serverless/blob/65e9860838de40c8ef0189c723e09936c8ca71a7/scripts/serverless.js#L577-L585) class
- Introduce `serverless.extendConfiguration(configurationPathKeys, value)` which should:
  - extend `configuration` with `value` at given `configurationPathKeys`
  - Parse value with `lib/configuration/variables/parse` and extend `variablesMeta` with it (taking into account `configurationPathKeys`) also remove any eventual existing meta at`configurationPathKeys`
  - Ensure that `serverless.extendConfiguration` throws error if invoked after `pluginManager.loadAllPlugins`  is run.

**Comment by mklenbw** [comment]
@icholy 
Any news on your work here?
Can we support you in some kind? This topic is really important for as, as we need to run on a modified serverless-version till it is implemented. This takes much more effort than implementing the feature ourselves.

**Comment by mklenbw** [comment]
Hey guys, i'm starting to work on this now. Blocked some time in my sprint and will dedicate my full time.
Can you please give me the permissions to do so?

**Comment by mklenbw** [comment]
>   * Ensure that `serverless.extendConfiguration` throws error if invoked after `pluginManager.loadAllPlugins`  is run.

Can you please explain this limitation?
Doesn't that mean i can't use the extension in any Plugin? How should i use it then?

**Comment by icholy** [comment]
@mklenbw it's all yours :)

**Comment by mklenbw** [comment]
> @mklenbw it's all yours :)

I'm already done. This works flawlessly. Didn't expect it to be that easy.
Now i'll need to add some tests as well.

**Comment by mklenbw** [comment]
@medikoo @mnapoli 
I finished implementing the feature with extensive testing.
How can i publish my branch and create a PR for you guys?

Should i add documentation for this feature and if yes in which path?

**Comment by medikoo** [comment]
@mklenbw No need for documentation, but ideally if it's covered by som test.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by icholy** [comment]
Is it possible to use this api to add items to an array?

**Comment by medikoo** [comment]
@icholy I believe you may rewrite given array property with new value. It may just raise issue if it's some very core property (as e.g. function events etc)

**Comment by mklenbw** [comment]
@icholy 
I did a check for types. On toplevel objects will be merged, arrays will be extended and trivial types will be assigned. As for my tests functions and resources arrays do not raise any issue.

**Comment by mklenbw** [comment]
@icholy @medikoo 

I just added my PR from a fork. I wanted to follow your guidelines on not using lodash but get/set method are just to handy. If you have alternatives just let me know. I'm looking forward to your review and suggestions.
