### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1246]
In this epic we're capturing all tasks for improved Java support including documentation and plugin development

- [x] Make Packaging mechanism more generic and move it into a separate plugin to support Java (see https://github.com/serverless/serverless/pull/1494)
- [x] Add a way to create template for different languages, runtimes and tools through `serverless create` (see https://github.com/serverless/serverless/pull/1536 and https://github.com/serverless/serverless/pull/1537)
- [x] Create template for Maven and Gradle with Java
- [x] Create documentation outlining Java Support and how to set it up

@license2e will help us looking into this as well

**Comment by license2e** [comment]
@flomotlik 
re: "Add a way to create template for different languages and tools through serverless create" 

Were you envisioning: 
`sls create function --name ... --provider aws --type java8` 
or  
`sls create --function ... --provider aws --type java8`
?

I currently have two new plugins created called Function and AwsFunction...

`sls function --name ... --provider aws --type java8` but I can switch it to work within the Create plugin...

**Comment by license2e** [comment]
> re: "Add a way to create template for different languages and tools through serverless create"

Nevermind, I saw issue number #1470 and created a PR for it #1491...  I will proceed with java8 template and template variants (eg. java8-gradle, etc).

**Comment by flomotlik** [comment]
@license2e we've moved ahead on our new template integration as well (thank you for your PR, it definitely influenced how we set it up) with #1537 and already implemented a first template for python with #1554 .

If you would still be able and like to contribute the Java templates for it that would be incredible. Happy to help in any way I can. We're currently planning to go implement something like described here: 

* http://docs.aws.amazon.com/lambda/latest/dg/create-deployment-pkg-zip-java.html
* http://docs.aws.amazon.com/lambda/latest/dg/java-create-jar-pkg-maven-no-ide.html

**Comment by hakandilek** [comment]
How does the timeline look with Gradle/Maven support? I can start earliest by the end of next week.

**Comment by flomotlik** [comment]
We would love to have it in by End of the month. We're doing a Team building next week and then in final week of July basically is where we'll take a close look. If you have time by then to take a look at it that would be awesome. I think this should be pretty easy and straight forward to do. /cc @license2e

**Comment by license2e** [comment]
@flomotlik Sorry about the delay, here it is: https://github.com/serverless/serverless/pull/1644

**Comment by pmuens** [comment]
Done with https://github.com/serverless/serverless/pull/1672
