### ISSUE TITLE
V1.0.0-beta.3 Discussion

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#1900]
- [ ] Other providers (IBM Openwhisk) - optional
- [x] Request/Response Codes and templates #1593
- [x] Logical ID of all resources #1869
- [x] Restructuring documentation (put documentation somewhere else as its hard to find and doesn't reflect the latest release) #1957
- [x] Serverless Variables syntax (and clearer description of Moving from serverless.yml) #1801
- [ ] serverless.json - optional
- [x] Adding Config File to deployed artifact and something like environment variables and encrypted config into the Lambda functions (documentation about service discovery) #1455
- [ ] Make sure plugins can access the provider plugin #1826 
- [x] Make deployment of other services very simple

**Comment by jthomerson** [comment]
Is this where we can comment if we feel that a particular issue should block the 1.0 final release? For me, #2046 makes 1.0.0-rc1 a no-go (my comments on that ticket about response templates and status codes).

**Comment by mthenw** [comment]
@flomotlik closing this on as it has been already released :)
