### ISSUE TITLE
Region handling should respect other config parameters and not set a default region

### ISSUE THREAD

**Issue by flomotlik** [serverless/serverless#2151]
# This is a Feature Proposal

## Description

Uses want to set the region that is used for deployment through various mechanisms:

* AWS_DEFAULT_REGION environment variable
* Region defined in profile
* Region variable in serverless.yml
* CLI option

At the moment as we do set a default if we don't find a region config in serverless.yml we remove many of those options, which sucks. We should support all default [AWS Variables](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment) without the user needing to do anything about it.

## Tasks

- [ ] Remove default region config
- [ ] Add region to every template file
- [ ] Add documentation to make it very clear how the Region config works
- [ ] Make sure profile regions are well supported

Similar or dependent issues:
* #2147
* #2078 
* #1707

**Comment by WooDzu** [comment]
Hi @flomotlik Just wanted to check with you if our current workflow will still appropriate for serverless.

At the moment we use only .credentials file and no AWS_* env variables and everybody have their own credentials pointing at different aws dev accounts but some also have additional profiles for [stage] and [production] accounts appropriate to their role.
These profile names are equal to stages which make configuration, this approach worked very well so far including for serverless where:

* `sls offline` starts the local plugin with [default] profile and default/local settings (eg. for dynamodb and other upstream servers). in credentials files [default] is always empty to prevent deploying local-development configurations by mistake to aws.

*`AWS_PROFILE=account1 sls deploy --stage account1`
*`AWS_PROFILE=stage sls deploy --stage stage`
*`AWS_PROFILE=production sls deploy --stage production`

are deploying to appropriate accounts. Extract is:
```yml
provider:
  name: aws
  runtime: nodejs4.3
  stage_default: default
  stage: ${opt:stage, self:provider.stage_default}
  region: eu-central-1
  profile: ${self:provider.stage}
```
we also extensively use `event.stage` in lambda functions but regions are always hardcoded. Any suggestions?

**Comment by flomotlik** [comment]
This should work exactly the same, no changes necessary I think. AWS_PROFILE will be AWS_DEFAULT_PROFILE, other than that the same.

**Comment by erikerikson** [comment]
Hadn't seen this but AWS_PROFILE is now supported in SLS, AWS_DEFAULT_PROFILE is not (unless it's been added).

**Comment by erikerikson** [comment]
impl here: https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L158

**Comment by erikerikson** [comment]
Ended up here because we had this come up with serverless-artillery.  a user wanted to use AWS_REGION or the default set in ~/.aws/config

**Comment by erikerikson** [comment]
These were supported in 0.x at some point

**Comment by pmuens** [comment]
@erikerikson thanks for the feedback! What's the status on this one? Does your awesome PR with the credential handling in the `awsProvider` plugin cover this?

**Comment by erikerikson** [comment]
@pmuens I don't think it does.  The approach I took there, regarding the region, was not to change anything about the prior impl.

**Comment by pmuens** [comment]
Ah ok. got it! Thanks for getting back! 👍

**Comment by medikoo** [comment]
I've updated description with proposal on how to coin this today

**Comment by et304383** [comment]
WHy is this issue still open and no comments in over 3 years?  This is STILL an issue.  Serverless needs to honour the environment variables that every SDK and the CLI already honour.
