### ISSUE TITLE
Config schema: Define AWS "provider" properties

### ISSUE THREAD

**Issue by medikoo** [serverless/serverless#8022]
### Use case description

It'll be nice to have `provider` section fully covered by schema validation (for AWS provider case)

### Proposed solution

Follow up to https://github.com/serverless/serverless/issues/6562, with which only schema placeholder for `provider` was configured.

Configuration should probably be done directly in: `lib/plugins/aws/provider/awsProvider.js`, what it covers was split into following issues:

- [x] #8016 Top level only properties
- [x]  #8017 Function related properties
- [x]  #8018 API Gateway related properties
- [x]  #8019 Websocket related properties
- [x]  #8020 ALB related properties
- [x]  #8021 HTTP API related properties
- [x]  #8031 S3 related properties

After all above issues are addressed, we may remove schema relaxation configured in `lib/classes/ConfigSchemaHandler/index.js`

**Comment by pgrzesik** [comment]
Hey @medikoo :wave: I think we have all of these crossed out - are we safe to close this issue now?

**Comment by medikoo** [comment]
@pgrzesik indeed, missed that! Great you've noticed. Closing
